# Generated by Django 3.1.7 on 2021-04-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone_number', models.IntegerField(default=0)),
                ('major1', models.CharField(choices=[('Biology', 'Biology'), ('Management', 'Management'), ('Computer Science', 'Computer Science')], max_length=20)),
                ('major2', models.CharField(choices=[('Biology', 'Biology'), ('Management', 'Management'), ('Computer Science', 'Computer Science')], max_length=20)),
                ('courses', models.TextField(blank=True)),
                ('housing_location', models.TextField(blank=True)),
                ('location', models.BooleanField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
